block.settings.schedule_builder:
  type: block_settings
  label: 'Schedule Builder block settings'
  mapping:
    search_context_selector:
      type: string
      label: 'Search context selector'
      nullable: true
    event_container_selector:
      type: string
      label: 'Event container selector'
    event_title_selector:
      type: string
      label: 'Event title selector'
    event_start_time_selector:
      type: string
      label: 'Event start time selector'
    event_end_time_selector:
      type: string
      label: 'Event end time selector'
    event_date_selector:
      type: string
      label: 'Event date selector'
      nullable: true
    event_location_selector:
      type: string
      label: 'Event location selector'
      nullable: true
    event_description_selector:
      type: string
      label: 'Event description selector'
      nullable: true
    event_link_selector:
      type: string
      label: 'Event link selector'
      nullable: true
    timezone:
      type: string
      label: 'Default timezone'
    localStorage_key:
      type: string
      label: 'LocalStorage key'
    ics_filename:
      type: string
      label: 'ICS filename'
    checkbox_position:
      type: string
      label: 'Checkbox position'
    checkbox_extra_classes:
      type: string
      label: 'Extra classes for checkbox'
      nullable: true
    download_button_label:
      type: string
      label: 'Download button label'
    download_button_extra_classes:
      type: string
      label: 'Extra classes for download button'
      nullable: true
    enable_selection_filter:
      type: boolean
      label: 'Enable selection filter'
    enable_select_actions:
      type: boolean
      label: 'Enable select actions'
    filter_extra_classes:
      type: string
      label: 'Extra classes for filter dropdown'
      nullable: true
    select_all_button_extra_classes:
      type: string
      label: 'Extra classes for select all button'
      nullable: true
    deselect_all_button_extra_classes:
      type: string
      label: 'Extra classes for deselect all button'
      nullable: true

